### ISSUE TITLE
My Profile > Account Settings and Email Notifications pages are blank

### ISSUE THREAD

**Issue by bree-z** [hard-g/openlab-bmcc#2] opened 2018-07-20 10:24 UTC
Hi Boone, 

When I go to My Profile > Account Settings or Email Notifications (e.g. http://openlabstage.bmcc.cuny.edu/members/openlab-testfacultybmcc-cuny-edu/settings/ or http://openlabstage.bmcc.cuny.edu/members/openlab-testfacultybmcc-cuny-edu/settings/notifications/ ) the pages are blank, and the right-hand sidebar is gone.  Same for:

http://openlabstage.bmcc.cuny.edu/members/openlab-testfacultybmcc-cuny-edu/settings/delete-account
http://openlabstage.bmcc.cuny.edu/members/openlab-testfacultybmcc-cuny-edu/invite-anyone/
http://openlabstage.bmcc.cuny.edu/members/openlab-testfacultybmcc-cuny-edu/invite-anyone/sent-invites/

<img width="1216" alt="screen shot 2018-07-20 at 1 19 48 pm" src="https://user-images.githubusercontent.com/7189824/42997509-a601fbb2-8c1f-11e8-9606-db6f5c378527.png">

**Comment by boonebgorges** [comment] 2018-07-20 13:16
This was caused by a change in BP that was triggering fatal errors. Fixed in openlab-theme and deployed here. https://github.com/cuny-academic-commons/openlab-theme/issues/245

**Closed by boonebgorges** 2018-07-20 13:16 UTC
